### ISSUE TITLE
Import issue with Geopandas

### ISSUE THREAD

**Issue by SBuxton-IDM** [SBuxton-IDM/EquityMilestone#8]
In the file https://github.com/SBuxton-IDM/EquityMilestone/blob/main/GeoPandas%20-%20Data%20-%20Spatial%20Join%20Notebook.ipynb we are seeing an import issue.

**Comment by SBuxton-IDM** [comment]
I believe this is due to a missing spatial indexing tool, should be fixed by either:
`!pip install pygeos` cell in the notebook, or installing via the development environment (like anaconda)

**Comment by SBuxton-IDM** [comment]
@jasonkronemeyer good to close?

**Comment by jasonkronemeyer** [comment]
Needed to shutdown jupyter notebook server in local dev env and install pygeos.
